/**
 * ANSI Shadow 字体的子集：只保留 `TODO-VUE` 用到的 7 个字母加空格。
 *
 * FIGfont 的字形是**按位置**排的（ASCII 32..126 依次各占一段，其后跟 7 个德语字符），
 * 所以删不得——删掉一个，后面全部错位。这里把用不到的字形换成空字形（本字体里那 7 个
 * 德语字符原本就是空的，格式上成立），位置一个不动。
 *
 * ⚠️ **改 `BRAND_NAME` 必须回来同步这个子集**，否则新字母会渲染成一片空白。
 * `tests/banner.test.ts` 逐字比对整幅字标，漏了会红。
 */
export default 'flf2a$ 7 7 13 0 7 0 64 0\nFont Author: ?\n\nMore Info:\n\nhttps://web.archive.org/web/20120819044459/http://www.roysac.com/thedrawfonts-tdf.asp\n\nFIGFont created with: http://patorjk.com/figfont-editor\n$  $@\n$  $@\n$  $@\n$  $@\n$  $@\n$  $@\n$  $@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n      @\n      @\n█████╗@\n╚════╝@\n      @\n      @\n      @@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n██████╗ @\n██╔══██╗@\n██║  ██║@\n██║  ██║@\n██████╔╝@\n╚═════╝ @\n        @@\n███████╗@\n██╔════╝@\n█████╗  @\n██╔══╝  @\n███████╗@\n╚══════╝@\n        @@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n ██████╗ @\n██╔═══██╗@\n██║   ██║@\n██║   ██║@\n╚██████╔╝@\n ╚═════╝ @\n         @@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n████████╗@\n╚══██╔══╝@\n   ██║   @\n   ██║   @\n   ██║   @\n   ╚═╝   @\n         @@\n██╗   ██╗@\n██║   ██║@\n██║   ██║@\n██║   ██║@\n╚██████╔╝@\n ╚═════╝ @\n         @@\n██╗   ██╗@\n██║   ██║@\n██║   ██║@\n╚██╗ ██╔╝@\n ╚████╔╝ @\n  ╚═══╝  @\n         @@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@\n@\n@\n@\n@\n@\n@\n@@'
